version: "3.8"

services:
  backend:
    build: .
    container_name: fairpay_hrm_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://db:27017
      - DATABASE_NAME=fairpay_hrm_db
    depends_on:
      - db
    volumes:
      - .:/app # Enable hot reloading by mounting the current directory

  db:
    image: mongo:latest
    container_name: fairpay_hrm_db
    ports:
      - "27017:27017" # Exposed to localhost for tools like Compass
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
